audio_settings:  # <--- Nueva clave de nivel superior
  # Audio recording settings (este comentario puede ir, o no)
  default_input_device_index: null
  default_output_device_index: null
  sample_rate: 44100
  chunk_size: 1024
  recording_format: paInt16 # Solo el nombre del formato
  channels: 1
  vad_enabled: True
  noise_reduction_enabled: True
